-- 코드를 입력하세요
SELECT 
    b.TITLE AS 'TITLE', 
    b.BOARD_ID AS 'BOARD_ID', 
    r.REPLY_ID AS 'REPLY_ID', 
    r.WRITER_ID AS 'WRITER_ID', 
    r.CONTENTS AS 'CONTENTS', 
    r.CREATED_DATE AS 'CREATED_DATE'
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_REPLY r
    ON LEFT(b.CREATED_DATE, 7) = '2022-10'
WHERE b.BOARD_ID = r.BOARD_ID
ORDER BY r.CREATED_DATE ASC, b.TITLE ASC